name: CI pipeline

on: 
  push: 
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      
      - name: install node 
        uses: actions/setup-node@v2
        with: 
          node-version: 22.14.0

      - name: install pnpm
        run: npm i -g pnpm

      - name: install dependencies
        run: pnpm install

      - name: build the code
        run: "cd apps/web && pnpm build" 